query prestashopCompanies($options: CompanyOptions) {
    companies(options: $options) {
        data {
            companyId
            name
            email
            img1
            slug
            address
            isConfirmed
            zipCode
            city
            vat
            country {
                countryId
                title
            }
            limits {
                active
                moduleId
                resource
                limit
                remaining
            }
        }
        errors {
            field
            msg
        }
    }
}
